import type { Settings, ThinkingLevel } from "./config-types.js";

export const DEFAULT_SETTINGS: Settings = {
  yoloMode: true,
  autoCompact: true,
  maxSessionCost: 0,
  showTokens: true,
  showCost: true,
  autoSaveSessions: true,
  enableThinking: false,
  thinkingLevel: "off" as ThinkingLevel,
  gitCheckpoints: true,
  notifyOnResponse: false,
  hideSidebar: false,
  autoRoute: true,
  scopedModels: [],
  favoriteThemes: [],
  lastModel: "",
  mode: "build",
  cavemanLevel: "auto",
  theme: "brokecli-dark",
  autoLint: false,
  autoTest: false,
  autoFixValidation: false,
  lintCommand: "npm run lint",
  testCommand: "npm test",
  deniedTools: [],
  disabledExtensions: [],
  quietStartup: false,
  editorPaddingX: 0,
  autocompleteMaxVisible: 5,
  showHardwareCursor: false,
  sessionDir: "",
  defaultThinkingLevel: "off",
  hideThinkingBlock: false,
  thinkingBudgets: {
    minimal: 1024,
    low: 4096,
    medium: 10240,
    high: 32768,
    xhigh: 65536,
  },
  compaction: {
    enabled: true,
    reserveTokens: 16384,
    keepRecentTokens: 20000,
  },
  branchSummary: {
    reserveTokens: 16384,
    skipPrompt: false,
  },
  retry: {
    enabled: true,
    maxRetries: 3,
    baseDelayMs: 2000,
    maxDelayMs: 60000,
  },
  terminal: {
    showImages: true,
    clearOnShrink: false,
  },
  images: {
    autoResize: true,
    blockImages: false,
  },
  shellPath: "",
  shellCommandPrefix: "",
  npmCommand: [],
  enabledModels: [],
  markdown: {
    codeBlockIndent: "  ",
  },
  packages: [],
  extensions: [],
  skills: [],
  prompts: [],
  themes: [],
  enableSkillCommands: true,
  discoverExtensions: true,
  discoverSkills: true,
  discoverPrompts: true,
  discoverThemes: true,
};
