import type { Settings, ThinkingLevel } from "./config-types.js";

export const DEFAULT_SETTINGS: Settings = {
  autoCompact: true,
  enablePromptCaching: true,
  enablePlannedScaffolds: false,
  memoizeToolResults: true,
  modelGeneratedSessionNames: false,
  showTokens: true,
  showCost: true,
  autoSaveSessions: true,
  enableThinking: false,
  thinkingLevel: "off" as ThinkingLevel,
  gitCheckpoints: false,
  notifyOnResponse: false,
  hideSidebar: false,
  autoRoute: false,
  scopedModels: [],
  lastModel: "",
  mode: "build",
  modeSwitching: "auto",
  cavemanLevel: "auto",
  autoLint: false,
  autoTest: false,
  autoFixValidation: false,
  lintCommand: "npm run lint",
  testCommand: "npm test",
  disabledTools: [],
  disabledExtensions: [],
  quietStartup: false,
  editorPaddingX: 0,
  autocompleteMaxVisible: 5,
  showHardwareCursor: false,
  sessionDir: "",
  hideThinkingBlock: false,
  thinkingBudgets: {
    minimal: 1024,
    low: 4096,
    medium: 10240,
    high: 32768,
    xhigh: 65536,
  },
  compaction: {
    enabled: true,
    triggerPercent: 80,
    reserveTokens: 16384,
    keepRecentTokens: 20000,
  },
  retry: {
    enabled: true,
    maxRetries: 3,
    baseDelayMs: 2000,
    maxDelayMs: 60000,
  },
  terminal: {
    showImages: true,
    clearOnShrink: false,
  },
  images: {
    blockImages: false,
  },
  npmCommand: [],
  markdown: {
    codeBlockIndent: "  ",
  },
  autonomy: {
    allowNetwork: true,
    allowReadOutsideWorkspace: false,
    allowWriteOutsideWorkspace: false,
    allowShellOutsideWorkspace: false,
    allowDestructiveShell: false,
    additionalReadRoots: [],
    additionalWriteRoots: [],
  },
  packages: [],
  extensions: [],
  skills: [],
  prompts: [],
  themes: [],
  theme: "brokecli",
  enableSkillCommands: true,
  discoverExtensions: true,
  discoverSkills: true,
  discoverPrompts: true,
  discoverThemes: true,
};
